#!/bin/sh                           
  if [ -f $HOME/.Xresources ]; then
      xrdb "$HOME/.Xresources"
  fi
  xsetroot -solid grey
  # Fix to make GNOME work
  export XKL_XMODMAP_DISABLE=1 
  /etc/X11/Xsession
  dbus-launch --exit-with-session startxfce4 &
